name: time_it

version: 1.1.0-dev
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: '>=3.16.2'

dependencies:
  audioplayers: ^5.2.1
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  meta: ^1.10.0
  package_info_plus: ^5.0.1
  riverpod: ^2.4.9
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  assets:
    - assets/audio/
  uses-material-design: true

# Run: flutter pub run flutter_launcher_icons:main
# Android adaptive icon is created manually using Asset Studio as this library
# doesn't support SVG.
flutter_icons:
  android: true
  image_path_android: images/launcher/stopwatch_android.png
  ios: true
  image_path_ios: images/launcher/stopwatch_ios.png
