name: time_it

version: 0.1.0-dev
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0
  meta: ^1.3.0
  quiver: ^3.0.0
  riverpod: ^0.14.0
  wakelock: ^0.5.0

flutter:
  uses-material-design: true
