name: time_it

version: 0.1.0-dev
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  audioplayers: ^0.19.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.3
  meta: ^1.3.0
  riverpod: ^1.0.0-dev.3
  wakelock: ^0.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  test: ^1.17.0

flutter:
  assets:
    - assets/audio/
  uses-material-design: true

# Run: flutter pub run flutter_launcher_icons:main
# Android adaptive icon is created manually using Asset Studio as this library
# doesn't support SVG.
flutter_icons:
  android: true
  image_path_android: images/launcher/stopwatch_android.png
  ios: true
  image_path_ios: images/launcher/stopwatch_ios.png
