name: time_it

version: 0.8.0
publish_to: none

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.13.5'

dependencies:
  audioplayers: ^4.1.0
  equatable: ^2.0.5
  # TODO: Check if the new version still needs the workaround in gradle.properties.
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.0-dev.7
  meta: ^1.9.1
  package_info_plus: ^4.1.0
  riverpod: 1.0.0-dev.7
  wakelock_plus: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  test: ^1.24.3

flutter:
  assets:
    - assets/audio/
  uses-material-design: true

# Run: flutter pub run flutter_launcher_icons:main
# Android adaptive icon is created manually using Asset Studio as this library
# doesn't support SVG.
flutter_icons:
  android: true
  image_path_android: images/launcher/stopwatch_android.png
  ios: true
  image_path_ios: images/launcher/stopwatch_ios.png
