name: time_it

version: 0.1.0-dev
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0
  meta: ^1.3.0
  quiver: ^3.0.0
  riverpod: ^0.14.0
  wakelock: ^0.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true

# Run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path_android: images/launcher/stopwatch_android.png
  ios: true
  image_path_ios: images/launcher/stopwatch_ios.png
