name: time_it

version: 1.1.0-dev
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.16.2"

dependencies:
  audioplayers: ^5.2.1
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  meta: ^1.10.0
  package_info_plus: ^5.0.1
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  wakelock_plus: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.24.9

flutter:
  assets:
    - assets/audio/
  uses-material-design: true

# Run: dart run flutter_launcher_icons
flutter_launcher_icons:
  # Android uses adaptive icons only, no need for PNG generation.
  android: false
  ios: true
  # Edit images/svg/stopwatch.svg in Inkscape:
  # - dimensions (80% scaled down): x: 83.2 y: 51.2 w: 345.6 h: 409.6
  # - color: Flutter theme primary color / Android launchForeground
  # - export:
  #   - no alpha channel
  #   - dimensions: 1024 x 1024
  #   - background color: Flutter theme background / Android launchBackground
  #   - file path: see below
  image_path_ios: images/svg/stopwatch.png
