name: main

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.1'
    - run: flutter pub get
    - run: flutter format --dry-run --set-exit-if-changed lib
    - run: flutter analyze
    - run: flutter build apk
